use super::{GoFloat64, GoInt, GoInt64, GoUint8, GoUintptr, LoadedSunnyNet};
use std::ffi::c_char;

#[allow(non_snake_case)]
impl LoadedSunnyNet {
    symbol_method!(JNI_OnLoad, "JNI_OnLoad", GoInt, (arg0: GoUintptr, arg1: GoUintptr));
    symbol_method!(GetSunnyVersion, "GetSunnyVersion", GoUintptr, ());
    symbol_method!(Free, "Free", void, (arg0: GoUintptr));
    symbol_method!(CreateSunnyNet, "CreateSunnyNet", GoInt, ());
    symbol_method!(ReleaseSunnyNet, "ReleaseSunnyNet", GoUint8, (arg0: GoInt));
    symbol_method!(SunnyNetStart, "SunnyNetStart", GoUint8, (arg0: GoInt));
    symbol_method!(SunnyNetSetPort, "SunnyNetSetPort", GoUint8, (arg0: GoInt, arg1: GoInt));
    symbol_method!(SunnyNetClose, "SunnyNetClose", GoUint8, (arg0: GoInt));
    symbol_method!(SunnyNetSetCert, "SunnyNetSetCert", GoUint8, (arg0: GoInt, arg1: GoInt));
    symbol_method!(SunnyNetInstallCert, "SunnyNetInstallCert", GoUintptr, (arg0: GoInt));
    symbol_method!(SunnyNetSetCallback, "SunnyNetSetCallback", GoUint8, (arg0: GoInt, arg1: GoInt, arg2: GoInt, arg3: GoInt, arg4: GoInt));
    symbol_method!(SunnyNetSocket5AddUser, "SunnyNetSocket5AddUser", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char));
    symbol_method!(SunnyNetVerifyUser, "SunnyNetVerifyUser", GoUint8, (arg0: GoInt, arg1: GoUint8));
    symbol_method!(SunnyNetSocket5DelUser, "SunnyNetSocket5DelUser", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(SunnyNetGetSocket5User, "SunnyNetGetSocket5User", GoUintptr, (arg0: GoInt));
    symbol_method!(SunnyNetMustTcp, "SunnyNetMustTcp", void, (arg0: GoInt, arg1: GoUint8));
    symbol_method!(CompileProxyRegexp, "CompileProxyRegexp", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(SetMustTcpRegexp, "SetMustTcpRegexp", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: GoUint8));
    symbol_method!(SunnyNetError, "SunnyNetError", GoUintptr, (arg0: GoInt));
    symbol_method!(SetGlobalProxy, "SetGlobalProxy", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: GoInt));
    symbol_method!(GetRequestProto, "GetRequestProto", GoUintptr, (arg0: GoInt));
    symbol_method!(GetResponseProto, "GetResponseProto", GoUintptr, (arg0: GoInt));
    symbol_method!(ExportCert, "ExportCert", GoUintptr, (arg0: GoInt));
    symbol_method!(SetHTTPRequestMaxUpdateLength, "SetHTTPRequestMaxUpdateLength", GoUint8, (arg0: GoInt, arg1: GoInt64));
    symbol_method!(SetIeProxy, "SetIeProxy", GoUint8, (arg0: GoInt));
    symbol_method!(CancelIEProxy, "CancelIEProxy", GoUint8, (arg0: GoInt));
    symbol_method!(SetRequestCookie, "SetRequestCookie", void, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char));
    symbol_method!(SetRequestAllCookie, "SetRequestAllCookie", void, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(GetRequestCookie, "GetRequestCookie", GoUintptr, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(GetRequestALLCookie, "GetRequestALLCookie", GoUintptr, (arg0: GoInt));
    symbol_method!(DelResponseHeader, "DelResponseHeader", void, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(DelRequestHeader, "DelRequestHeader", void, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(SetRequestOutTime, "SetRequestOutTime", void, (arg0: GoInt, arg1: GoInt));
    symbol_method!(SetRequestALLHeader, "SetRequestALLHeader", void, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(SetRequestHeader, "SetRequestHeader", void, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char));
    symbol_method!(RandomRequestCipherSuites, "RandomRequestCipherSuites", GoUint8, (arg0: GoInt));
    symbol_method!(SetRequestHTTP2Config, "SetRequestHTTP2Config", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(SetResponseHeader, "SetResponseHeader", void, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char));
    symbol_method!(GetRequestHeader, "GetRequestHeader", GoUintptr, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(GetResponseHeader, "GetResponseHeader", GoUintptr, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(GetResponseServerAddress, "GetResponseServerAddress", GoUintptr, (arg0: GoInt));
    symbol_method!(SetResponseAllHeader, "SetResponseAllHeader", void, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(GetResponseAllHeader, "GetResponseAllHeader", GoUintptr, (arg0: GoInt));
    symbol_method!(GetRequestAllHeader, "GetRequestAllHeader", GoUintptr, (arg0: GoInt));
    symbol_method!(SetRequestProxy, "SetRequestProxy", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: GoInt));
    symbol_method!(GetResponseStatusCode, "GetResponseStatusCode", GoInt, (arg0: GoInt));
    symbol_method!(GetRequestClientIp, "GetRequestClientIp", GoUintptr, (arg0: GoInt));
    symbol_method!(GetResponseStatus, "GetResponseStatus", GoUintptr, (arg0: GoInt));
    symbol_method!(SetResponseStatus, "SetResponseStatus", void, (arg0: GoInt, arg1: GoInt));
    symbol_method!(SetRequestUrl, "SetRequestUrl", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(GetRequestBodyLen, "GetRequestBodyLen", GoInt, (arg0: GoInt));
    symbol_method!(GetResponseBodyLen, "GetResponseBodyLen", GoInt, (arg0: GoInt));
    symbol_method!(SetResponseData, "SetResponseData", GoUint8, (arg0: GoInt, arg1: GoUintptr, arg2: GoInt));
    symbol_method!(SetRequestData, "SetRequestData", GoUint8, (arg0: GoInt, arg1: GoUintptr, arg2: GoInt));
    symbol_method!(GetRequestBody, "GetRequestBody", GoUintptr, (arg0: GoInt));
    symbol_method!(IsRequestRawBody, "IsRequestRawBody", GoUint8, (arg0: GoInt));
    symbol_method!(RawRequestDataToFile, "RawRequestDataToFile", GoUint8, (arg0: GoInt, arg1: GoUintptr, arg2: GoInt));
    symbol_method!(GetResponseBody, "GetResponseBody", GoUintptr, (arg0: GoInt));
    symbol_method!(GetWebsocketBodyLen, "GetWebsocketBodyLen", GoInt, (arg0: GoInt));
    symbol_method!(CloseWebsocket, "CloseWebsocket", GoUint8, (arg0: GoInt));
    symbol_method!(GetMessageNote, "GetMessageNote", GoUintptr, (arg0: GoInt));
    symbol_method!(GetWebsocketBody, "GetWebsocketBody", GoUintptr, (arg0: GoInt));
    symbol_method!(SetWebsocketBody, "SetWebsocketBody", GoUint8, (arg0: GoInt, arg1: GoUintptr, arg2: GoInt));
    symbol_method!(SendWebsocketBody, "SendWebsocketBody", GoUint8, (arg0: GoInt, arg1: GoInt, arg2: GoUintptr, arg3: GoInt));
    symbol_method!(SendWebsocketClientBody, "SendWebsocketClientBody", GoUint8, (arg0: GoInt, arg1: GoInt, arg2: GoUintptr, arg3: GoInt));
    symbol_method!(SetTcpBody, "SetTcpBody", GoUint8, (arg0: GoInt, arg1: GoInt, arg2: GoUintptr, arg3: GoInt));
    symbol_method!(SetTcpAgent, "SetTcpAgent", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: GoInt));
    symbol_method!(TcpCloseClient, "TcpCloseClient", GoUint8, (arg0: GoInt));
    symbol_method!(SetTcpConnectionIP, "SetTcpConnectionIP", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(TcpSendMsg, "TcpSendMsg", GoInt, (arg0: GoInt, arg1: GoUintptr, arg2: GoInt));
    symbol_method!(TcpSendMsgClient, "TcpSendMsgClient", GoInt, (arg0: GoInt, arg1: GoUintptr, arg2: GoInt));
    symbol_method!(BytesToInt, "BytesToInt", GoInt, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(GzipUnCompress, "GzipUnCompress", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(BrUnCompress, "BrUnCompress", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(BrCompress, "BrCompress", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(ZSTDDecompress, "ZSTDDecompress", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(ZSTDCompress, "ZSTDCompress", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(BrotliCompress, "BrotliCompress", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(GzipCompress, "GzipCompress", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(ZlibCompress, "ZlibCompress", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(ZlibUnCompress, "ZlibUnCompress", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(DeflateUnCompress, "DeflateUnCompress", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(DeflateCompress, "DeflateCompress", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(WebpToJpegBytes, "WebpToJpegBytes", GoUintptr, (arg0: GoUintptr, arg1: GoInt, arg2: GoInt));
    symbol_method!(WebpToPngBytes, "WebpToPngBytes", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(WebpToJpeg, "WebpToJpeg", GoUint8, (arg0: *const c_char, arg1: *const c_char, arg2: GoInt));
    symbol_method!(WebpToPng, "WebpToPng", GoUint8, (arg0: *const c_char, arg1: *const c_char));
    symbol_method!(OpenDrive, "OpenDrive", GoUint8, (arg0: GoInt, arg1: GoInt));
    symbol_method!(UnDrive, "UnDrive", void, (arg0: GoInt));
    symbol_method!(ProcessAddName, "ProcessAddName", void, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(ProcessDelName, "ProcessDelName", void, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(ProcessAddPid, "ProcessAddPid", void, (arg0: GoInt, arg1: GoInt));
    symbol_method!(ProcessDelPid, "ProcessDelPid", void, (arg0: GoInt, arg1: GoInt));
    symbol_method!(ProcessCancelAll, "ProcessCancelAll", void, (arg0: GoInt));
    symbol_method!(ProcessALLName, "ProcessALLName", void, (arg0: GoInt, arg1: GoUint8, arg2: GoUint8));
    symbol_method!(GetCommonName, "GetCommonName", GoUintptr, (arg0: GoInt));
    symbol_method!(ExportP12, "ExportP12", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char));
    symbol_method!(ExportPub, "ExportPub", GoUintptr, (arg0: GoInt));
    symbol_method!(ExportKEY, "ExportKEY", GoUintptr, (arg0: GoInt));
    symbol_method!(ExportCA, "ExportCA", GoUintptr, (arg0: GoInt));
    symbol_method!(CreateCA, "CreateCA", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char, arg3: *const c_char, arg4: *const c_char, arg5: *const c_char, arg6: *const c_char, arg7: GoInt, arg8: GoInt));
    symbol_method!(AddClientAuth, "AddClientAuth", GoUint8, (arg0: GoInt, arg1: GoInt));
    symbol_method!(SetCipherSuites, "SetCipherSuites", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(AddCertPoolText, "AddCertPoolText", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(AddCertPoolPath, "AddCertPoolPath", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(GetServerName, "GetServerName", GoUintptr, (arg0: GoInt));
    symbol_method!(SetServerName, "SetServerName", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(SetInsecureSkipVerify, "SetInsecureSkipVerify", GoUint8, (arg0: GoInt, arg1: GoUint8));
    symbol_method!(LoadX509Certificate, "LoadX509Certificate", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char, arg3: *const c_char));
    symbol_method!(LoadX509KeyPair, "LoadX509KeyPair", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char));
    symbol_method!(LoadP12Certificate, "LoadP12Certificate", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char));
    symbol_method!(RemoveCertificate, "RemoveCertificate", void, (arg0: GoInt));
    symbol_method!(CreateCertificate, "CreateCertificate", GoInt, ());
    symbol_method!(KeysWriteStr, "KeysWriteStr", void, (arg0: GoInt, arg1: *const c_char, arg2: GoUintptr, arg3: GoInt));
    symbol_method!(KeysGetJson, "KeysGetJson", GoUintptr, (arg0: GoInt));
    symbol_method!(KeysGetCount, "KeysGetCount", GoInt, (arg0: GoInt));
    symbol_method!(KeysEmpty, "KeysEmpty", void, (arg0: GoInt));
    symbol_method!(KeysReadInt, "KeysReadInt", GoInt, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(KeysWriteInt, "KeysWriteInt", void, (arg0: GoInt, arg1: *const c_char, arg2: GoInt));
    symbol_method!(KeysReadLong, "KeysReadLong", GoInt64, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(KeysWriteLong, "KeysWriteLong", void, (arg0: GoInt, arg1: *const c_char, arg2: GoInt64));
    symbol_method!(KeysReadFloat, "KeysReadFloat", GoFloat64, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(KeysWriteFloat, "KeysWriteFloat", void, (arg0: GoInt, arg1: *const c_char, arg2: GoFloat64));
    symbol_method!(KeysWrite, "KeysWrite", void, (arg0: GoInt, arg1: *const c_char, arg2: GoUintptr, arg3: GoInt));
    symbol_method!(KeysRead, "KeysRead", GoUintptr, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(KeysDelete, "KeysDelete", void, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(RemoveKeys, "RemoveKeys", void, (arg0: GoInt));
    symbol_method!(CreateKeys, "CreateKeys", GoInt, ());
    symbol_method!(HTTPSetH2Config, "HTTPSetH2Config", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(HTTPSetRandomTLS, "HTTPSetRandomTLS", GoUint8, (arg0: GoInt, arg1: GoUint8));
    symbol_method!(HTTPSetRedirect, "HTTPSetRedirect", GoUint8, (arg0: GoInt, arg1: GoUint8));
    symbol_method!(HTTPGetCode, "HTTPGetCode", GoInt, (arg0: GoInt));
    symbol_method!(HTTPSetCertManager, "HTTPSetCertManager", GoUint8, (arg0: GoInt, arg1: GoInt));
    symbol_method!(HTTPGetBody, "HTTPGetBody", GoUintptr, (arg0: GoInt));
    symbol_method!(HTTPGetHeader, "HTTPGetHeader", GoUintptr, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(HTTPGetRequestHeader, "HTTPGetRequestHeader", GoUintptr, (arg0: GoInt));
    symbol_method!(HTTPGetHeads, "HTTPGetHeads", GoUintptr, (arg0: GoInt));
    symbol_method!(HTTPGetBodyLen, "HTTPGetBodyLen", GoInt, (arg0: GoInt));
    symbol_method!(HTTPSendBin, "HTTPSendBin", void, (arg0: GoInt, arg1: GoUintptr, arg2: GoInt));
    symbol_method!(HTTPSetTimeouts, "HTTPSetTimeouts", void, (arg0: GoInt, arg1: GoInt));
    symbol_method!(HTTPSetServerIP, "HTTPSetServerIP", void, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(HTTPSetProxyIP, "HTTPSetProxyIP", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(HTTPSetHeader, "HTTPSetHeader", void, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char));
    symbol_method!(HTTPOpen, "HTTPOpen", void, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char));
    symbol_method!(RemoveHTTPClient, "RemoveHTTPClient", void, (arg0: GoInt));
    symbol_method!(CreateHTTPClient, "CreateHTTPClient", GoInt, ());
    symbol_method!(JsonToPB, "JsonToPB", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(PbToJson, "PbToJson", GoUintptr, (arg0: GoUintptr, arg1: GoInt));
    symbol_method!(QueuePull, "QueuePull", GoUintptr, (arg0: *const c_char));
    symbol_method!(QueuePush, "QueuePush", void, (arg0: *const c_char, arg1: GoUintptr, arg2: GoInt));
    symbol_method!(QueueLength, "QueueLength", GoInt, (arg0: *const c_char));
    symbol_method!(QueueRelease, "QueueRelease", void, (arg0: *const c_char));
    symbol_method!(QueueIsEmpty, "QueueIsEmpty", GoUint8, (arg0: *const c_char));
    symbol_method!(CreateQueue, "CreateQueue", void, (arg0: *const c_char));
    symbol_method!(SocketClientWrite, "SocketClientWrite", GoInt, (arg0: GoInt, arg1: GoInt, arg2: GoUintptr, arg3: GoInt));
    symbol_method!(SocketClientClose, "SocketClientClose", void, (arg0: GoInt));
    symbol_method!(SocketClientReceive, "SocketClientReceive", GoUintptr, (arg0: GoInt, arg1: GoInt));
    symbol_method!(SocketClientDial, "SocketClientDial", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: GoInt, arg3: GoUint8, arg4: GoUint8, arg5: *const c_char, arg6: GoInt, arg7: GoInt, arg8: *const c_char));
    symbol_method!(SocketClientSetBufferSize, "SocketClientSetBufferSize", GoUint8, (arg0: GoInt, arg1: GoInt));
    symbol_method!(SocketClientGetErr, "SocketClientGetErr", GoUintptr, (arg0: GoInt));
    symbol_method!(RemoveSocketClient, "RemoveSocketClient", void, (arg0: GoInt));
    symbol_method!(CreateSocketClient, "CreateSocketClient", GoInt, ());
    symbol_method!(WebsocketClientReceive, "WebsocketClientReceive", GoUintptr, (arg0: GoInt, arg1: GoInt));
    symbol_method!(WebsocketReadWrite, "WebsocketReadWrite", GoUint8, (arg0: GoInt, arg1: GoUintptr, arg2: GoInt, arg3: GoInt));
    symbol_method!(WebsocketClose, "WebsocketClose", void, (arg0: GoInt));
    symbol_method!(WebsocketHeartbeat, "WebsocketHeartbeat", void, (arg0: GoInt, arg1: GoInt, arg2: GoInt));
    symbol_method!(WebsocketDial, "WebsocketDial", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char, arg3: GoInt, arg4: GoUint8, arg5: *const c_char, arg6: GoInt, arg7: GoInt, arg8: *const c_char));
    symbol_method!(WebsocketGetErr, "WebsocketGetErr", GoUintptr, (arg0: GoInt));
    symbol_method!(RemoveWebsocket, "RemoveWebsocket", void, (arg0: GoInt));
    symbol_method!(CreateWebsocket, "CreateWebsocket", GoInt, ());
    symbol_method!(AddHttpCertificate, "AddHttpCertificate", GoUint8, (arg0: *const c_char, arg1: GoInt, arg2: GoInt));
    symbol_method!(DelHttpCertificate, "DelHttpCertificate", void, (arg0: *const c_char));
    symbol_method!(RedisSubscribe, "RedisSubscribe", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: GoInt, arg3: GoUint8));
    symbol_method!(RedisDelete, "RedisDelete", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(RedisFlushDB, "RedisFlushDB", void, (arg0: GoInt));
    symbol_method!(RedisFlushAll, "RedisFlushAll", void, (arg0: GoInt));
    symbol_method!(RedisClose, "RedisClose", void, (arg0: GoInt));
    symbol_method!(RedisGetInt, "RedisGetInt", GoInt64, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(RedisGetKeys, "RedisGetKeys", GoUintptr, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(RedisDo, "RedisDo", GoUintptr, (arg0: GoInt, arg1: *const c_char, arg2: GoUintptr));
    symbol_method!(RedisGetStr, "RedisGetStr", GoUintptr, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(RedisGetBytes, "RedisGetBytes", GoUintptr, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(RedisExists, "RedisExists", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(RedisSetNx, "RedisSetNx", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char, arg3: GoInt));
    symbol_method!(RedisSet, "RedisSet", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char, arg3: GoInt));
    symbol_method!(RedisSetBytes, "RedisSetBytes", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: GoUintptr, arg3: GoInt, arg4: GoInt));
    symbol_method!(RedisDial, "RedisDial", GoUint8, (arg0: GoInt, arg1: *const c_char, arg2: *const c_char, arg3: GoInt, arg4: GoInt, arg5: GoInt, arg6: GoInt, arg7: GoInt, arg8: GoInt, arg9: GoInt, arg10: GoInt, arg11: GoInt, arg12: GoUintptr));
    symbol_method!(RemoveRedis, "RemoveRedis", void, (arg0: GoInt));
    symbol_method!(CreateRedis, "CreateRedis", GoInt, ());
    symbol_method!(SetUdpData, "SetUdpData", GoUint8, (arg0: GoInt, arg1: GoUintptr, arg2: GoInt));
    symbol_method!(GetUdpData, "GetUdpData", GoUintptr, (arg0: GoInt));
    symbol_method!(UdpSendToClient, "UdpSendToClient", GoUint8, (arg0: GoInt, arg1: GoUintptr, arg2: GoInt));
    symbol_method!(UdpSendToServer, "UdpSendToServer", GoUint8, (arg0: GoInt, arg1: GoUintptr, arg2: GoInt));
    symbol_method!(SetScriptCode, "SetScriptCode", GoUintptr, (arg0: GoInt, arg1: GoUintptr, arg2: GoInt));
    symbol_method!(SetScriptCall, "SetScriptCall", void, (arg0: GoInt, arg1: GoUintptr, arg2: GoUintptr));
    symbol_method!(SetScriptPage, "SetScriptPage", GoUintptr, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(DisableTCP, "DisableTCP", GoUint8, (arg0: GoInt, arg1: GoUint8));
    symbol_method!(DisableUDP, "DisableUDP", GoUint8, (arg0: GoInt, arg1: GoUint8));
    symbol_method!(SetRandomTLS, "SetRandomTLS", GoUint8, (arg0: GoInt, arg1: GoUint8));
    symbol_method!(SetDnsServer, "SetDnsServer", void, (arg0: *const c_char));
    symbol_method!(SetOutRouterIP, "SetOutRouterIP", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(RequestSetOutRouterIP, "RequestSetOutRouterIP", GoUint8, (arg0: GoInt, arg1: *const c_char));
    symbol_method!(HTTPSetOutRouterIP, "HTTPSetOutRouterIP", GoUint8, (arg0: GoInt, arg1: *const c_char));
}
